{% extends "layouts/app.twig" %}

{% block title %} Nero - there was an error {% endblock %}

{% block content %}
    <div class="container exception-view">
	<!-- Heading -->
	<div class="row">
	    <h1>Nero Exception</h1>
	    <h3>{{ exception_name }} : {{ exception_message }}</h3>
	    <p>On line {{ exception_line }} in {{ exception_file }}</p>

	</div>

	<!-- Stack trace -->
	<div class="row">
            <p>Stack trace: </p>

	    <ul class="list-group">
                {% for line in trace %}
                    <li class="list-group-item">{{ line }}</li>
		{% endfor %}
	    </ul>
	</div>
    </div>
{% endblock %}
